# This file has been generated by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, buildNeovimPluginFrom2Nix, fetchFromGitHub, fetchgit }:

final: prev:
{
  ddc-filter-matcher_head = buildVimPluginFrom2Nix {
    pname = "ddc-filter-matcher_head";
    version = "2023-05-21";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_head";
      rev = "16727bb785c7fdbd4c5ed7a5f3da8d2f7355f8fd";
      sha256 = "136sz3vjgkksl3sq5jzccahymi0rzqqsjmycf23pnxv4kzflwkag";
    };
    meta.homepage = "https://github.com/Shougo/ddc-filter-matcher_head/";
  };

  ddc-filter-sorter_rank = buildVimPluginFrom2Nix {
    pname = "ddc-filter-sorter_rank";
    version = "2023-09-11";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_rank";
      rev = "fccbd5892dc57f44f07cddcbef9d465838b36cee";
      sha256 = "1cs4c7q8r60q7pxacl0f091ap9kjsqmc19mlb2rwrwi76v6x1avs";
    };
    meta.homepage = "https://github.com/Shougo/ddc-filter-sorter_rank/";
  };

  ddc-source-nvim-lsp = buildVimPluginFrom2Nix {
    pname = "ddc-source-nvim-lsp";
    version = "2023-10-09";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-nvim-lsp";
      rev = "d203bb9c6160f9bd540692d6b857283af88bae3e";
      sha256 = "1qymadmijy8jcx4dbvs5v9pc2qalqjhgjaabi08x562fpdd1jc5m";
    };
    meta.homepage = "https://github.com/Shougo/ddc-source-nvim-lsp/";
  };

  ddc-ui-native = buildVimPluginFrom2Nix {
    pname = "ddc-ui-native";
    version = "2023-10-19";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-native";
      rev = "43e7ea7231afdd35fc5b96d1cf16a73069c28636";
      sha256 = "0lcjf3l6k3mmxs4m5zpffbii9qvdbc01njahkpkah3nyywpcl44z";
    };
    meta.homepage = "https://github.com/Shougo/ddc-ui-native/";
  };

  ddc-ui-pum = buildVimPluginFrom2Nix {
    pname = "ddc-ui-pum";
    version = "2023-10-07";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "6fd98ba227889883bbf75405506c451feaae6ef8";
      sha256 = "1yy572i672ha5zlxkda6lv5mp2y5yq0sd1ffpa6my59rzv86ixr7";
    };
    meta.homepage = "https://github.com/Shougo/ddc-ui-pum/";
  };

  ddc-vim = buildVimPluginFrom2Nix {
    pname = "ddc.vim";
    version = "2023-10-15";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "2c13eff071fd4c96486506ab5253e8d40a076c88";
      sha256 = "0c090f3xjz2chcsx2jc5834sdghwsxf784jlz02d70is26cl22y5";
    };
    meta.homepage = "https://github.com/Shougo/ddc.vim/";
  };

  denops-vim = buildVimPluginFrom2Nix {
    pname = "denops.vim";
    version = "2023-10-22";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "37196f18758e6ba16189f9814369ae89b749fbde";
      sha256 = "169m1jfsk4gari7qqnzvil7rcwma8g9w51lyh2rcficx7148v5fj";
    };
    meta.homepage = "https://github.com/vim-denops/denops.vim/";
  };

  pum-vim = buildVimPluginFrom2Nix {
    pname = "pum.vim";
    version = "2023-10-15";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "e787cecb4272c8a8efdeb3b1ad32a90a5747a7a2";
      sha256 = "0madmmaadsad63ji37p4sb0qr1mlvjaw6jyk1yx64ifhyl4wkg51";
    };
    meta.homepage = "https://github.com/Shougo/pum.vim/";
  };

  skkeleton = buildVimPluginFrom2Nix {
    pname = "skkeleton";
    version = "2023-10-21";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "e5e1aaab50db4418116d89b453b24b9b8a0a7997";
      sha256 = "0xmjk0n7kblzw4hcizz9isqvvl5r6vjm1vh8qkfp4x6h3pqd44rp";
    };
    meta.homepage = "https://github.com/vim-skk/skkeleton/";
  };


}
