# This file has been generated by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, buildNeovimPluginFrom2Nix, fetchFromGitHub, fetchgit }:

final: prev:
{
  ddc-filter-matcher_head = buildVimPluginFrom2Nix {
    pname = "ddc-filter-matcher_head";
    version = "2023-03-01";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_head";
      rev = "fd27c8881e677048218441eeb0566c334548426d";
      sha256 = "0jqf8w6qfzky67mbdi45k4xy9ziw544k5prqnicnqz21j4m2q8gq";
    };
    meta.homepage = "https://github.com/Shougo/ddc-filter-matcher_head/";
  };

  ddc-filter-sorter_rank = buildVimPluginFrom2Nix {
    pname = "ddc-filter-sorter_rank";
    version = "2023-03-01";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_rank";
      rev = "db14b0450e27f9117e6983879ce5c81efe26d89f";
      sha256 = "0dppb60a5gjb2103j4iymcdiqk3x13cjs8939viqrsl9c5r29h2d";
    };
    meta.homepage = "https://github.com/Shougo/ddc-filter-sorter_rank/";
  };

  ddc-source-nvim-lsp = buildVimPluginFrom2Nix {
    pname = "ddc-source-nvim-lsp";
    version = "2022-11-24";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-nvim-lsp";
      rev = "1795bfdbf0879054f3ca9f5ab7025ba68e0338c4";
      sha256 = "0c3k9snjva0ibacc098h0b088p02fd0nmmsdfdr3m0784jlzvxbm";
    };
    meta.homepage = "https://github.com/Shougo/ddc-source-nvim-lsp/";
  };

  ddc-ui-native = buildVimPluginFrom2Nix {
    pname = "ddc-ui-native";
    version = "2023-03-03";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-native";
      rev = "5ff6a1b887c26b3ad9d5085941e6472716703a5e";
      sha256 = "0hxgl49iq0a0advs4lmam66hgc8hr1bakhj75ixsd4brp787w5wf";
    };
    meta.homepage = "https://github.com/Shougo/ddc-ui-native/";
  };

  ddc-ui-pum = buildVimPluginFrom2Nix {
    pname = "ddc-ui-pum";
    version = "2023-02-05";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "aa027c94834226170f03ba7cff5d25293f23a666";
      sha256 = "1g7xhxrs1cl89ib03w3s3s6pv51y6j82psdmzpj9pc7wg9s40nfi";
    };
    meta.homepage = "https://github.com/Shougo/ddc-ui-pum/";
  };

  ddc-vim = buildVimPluginFrom2Nix {
    pname = "ddc.vim";
    version = "2023-03-20";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "7934347b9b74eab5b19a099f8d826862eea8beee";
      sha256 = "0g9ahp8090h9p2yz6yz9rg1m35www4mxg6gdbpz5plah9hr7mas1";
    };
    meta.homepage = "https://github.com/Shougo/ddc.vim/";
  };

  denops-vim = buildVimPluginFrom2Nix {
    pname = "denops.vim";
    version = "2023-02-01";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "8f3899de3d3add07105221262dca90a31c4c2d4c";
      sha256 = "1whi5mc1hjfmhnrr2w5qsp211l0jq9q7mcvqyrf5vxcrd83raxrr";
    };
    meta.homepage = "https://github.com/vim-denops/denops.vim/";
  };

  pum-vim = buildVimPluginFrom2Nix {
    pname = "pum.vim";
    version = "2023-03-21";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "62bf08112003b91e2ad9858abf3654f8e6678d7a";
      sha256 = "15jizg640bcny5z8b7mrnnlfv23kckijc5v7s28x3xm0arl1ydpv";
    };
    meta.homepage = "https://github.com/Shougo/pum.vim/";
  };

  skkeleton = buildVimPluginFrom2Nix {
    pname = "skkeleton";
    version = "2023-03-19";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "00b227cbce6ab74de0869346a2b24b0f43efedfc";
      sha256 = "0w249rrz18xh70mfsrvigd4bi87p4m5z21gjkza69hi6v8n4c7h2";
    };
    meta.homepage = "https://github.com/vim-skk/skkeleton/";
  };


}
