# This file has been generated by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, buildNeovimPluginFrom2Nix, fetchFromGitHub, fetchgit }:

final: prev:
{
  ddc-matcher_head = buildVimPluginFrom2Nix {
    pname = "ddc-matcher_head";
    version = "2022-11-24";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-matcher_head";
      rev = "470cd38e80e935e3ade8389a1de686266b2e1c56";
      sha256 = "1hzzvy6hfwjs8aaz5z2ixqbb9z49v8k2v81pnz57g4h2a8qnjs59";
    };
    meta.homepage = "https://github.com/Shougo/ddc-matcher_head/";
  };

  ddc-source-nvim-lsp = buildVimPluginFrom2Nix {
    pname = "ddc-nvim-lsp";
    version = "2022-11-24";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-nvim-lsp";
      rev = "1795bfdbf0879054f3ca9f5ab7025ba68e0338c4";
      sha256 = "0c3k9snjva0ibacc098h0b088p02fd0nmmsdfdr3m0784jlzvxbm";
    };
    meta.homepage = "https://github.com/Shougo/ddc-source-nvim-lsp/";
  };

  ddc-sorter_rank = buildVimPluginFrom2Nix {
    pname = "ddc-sorter_rank";
    version = "2022-11-24";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-sorter_rank";
      rev = "412c0f039d1690978089cac479f71d393135a2ba";
      sha256 = "1k9b70r7yjp8wzjl64387wq7qgy5zq600z02ijmqcdwhg0cbxp77";
    };
    meta.homepage = "https://github.com/Shougo/ddc-sorter_rank/";
  };

  ddc-vim = buildVimPluginFrom2Nix {
    pname = "ddc.vim";
    version = "2022-11-29";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "a765300420e5a166be5f24ea608b528b178c6cc8";
      sha256 = "1hhzmvwzl9kwfjlj04pbfh54wda1vd8vahj8i80b4cvy3b24h0k7";
    };
    meta.homepage = "https://github.com/Shougo/ddc.vim/";
  };

  denops-vim = buildVimPluginFrom2Nix {
    pname = "denops.vim";
    version = "2022-12-01";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "30286cfc8833c1b5b716b69493c69b7cb6a8922e";
      sha256 = "163rxrdkg267fz03rjhixf7ich0jbsl3rdp79vi49jc9psrnp7bc";
    };
    meta.homepage = "https://github.com/vim-denops/denops.vim/";
  };

  pum-vim = buildVimPluginFrom2Nix {
    pname = "pum.vim";
    version = "2022-11-27";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "31aae8d39061bcdae755e468e83a3a70b72a0fce";
      sha256 = "109jhfmvmnm1qkghjw62c95gj0k5f2j9lnpdq2pcpdjdng05rmyz";
    };
    meta.homepage = "https://github.com/Shougo/pum.vim/";
  };

  skkeleton = buildVimPluginFrom2Nix {
    pname = "skkeleton";
    version = "2022-12-01";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "0a1fdd399cec1981ef2ef5e64402f1c3dec08cbe";
      sha256 = "1i41759aclwn8z8cbc5gp5dxqsn69wmajpfx0zdyql8rc183xlv9";
    };
    meta.homepage = "https://github.com/vim-skk/skkeleton/";
  };


}
